# Build Stage
FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Run Stage
FROM openjdk:17-jre-slim
WORKDIR /app
COPY --from=build /app/target/clicknbuy.jar .
EXPOSE 8080
CMD ["java", "-jar", "clicknbuy.jar"]
